# Generated by Django 6.0.2 on 2026-03-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_character_opening_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_character',
            field=models.BooleanField(default=True, verbose_name='可创建角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_publish_character',
            field=models.BooleanField(default=True, verbose_name='可发布角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='超级管理员'),
        ),
    ]
